### ISSUE TITLE
Define and implement footer

### ISSUE THREAD

**Issue by guiocavalcanti** [geteloquent/geteloquent.github.io#3]
As Eloquent site developer I'd like to include the footer in any new page I'm going to create.

**Comment by yeltsin** [comment]
Se encontra aqui no source: https://github.com/geteloquent/geteloquent.github.io/blob/c45e2cfe5bfbf54c7299d0c786e587b353dca8d2/source/_footer.erb E está incluso em todas as páginas novas criadas. Sofrerá nova modificação?

**Comment by filipewl** [comment]
Done. You just need to use one of these [two layouts](https://github.com/geteloquent/geteloquent.github.io/pull/25/files#diff-df6342cb406fe6a93f1a9c9180a53067): hero (used in the home page) and layout (used for other pages). Both include the footer.
