### ISSUE TITLE
Implement home page

### ISSUE THREAD

**Issue by guiocavalcanti** [geteloquent/geteloquent.github.io#4]
![01_home](https://cloud.githubusercontent.com/assets/188599/2816904/a72a5d78-ced1-11e3-9e60-3db668757a33.png)
![01](https://cloud.githubusercontent.com/assets/188599/2817312/c5955456-ced7-11e3-8bfb-ef5f7f6b3345.png)

PSD: https://www.dropbox.com/s/m5ckf1qtertvzw2/layout.psd

**Comment by yeltsin** [comment]
Com exceção do layout mobile (o "header" se encontra meio problemático), o layout para desktops está concluído. Estou trabalhando primeiro na versão desktop para depois otimizar para mobile. :)

**Comment by filipewl** [comment]
Fixed in #14, #15, #17 and #16.
